rhq-project/rhq

modules/core/domain/pom.xml, modules/enterprise/remoting/client-deps/pom.xml, modules/enterprise/server/jar/pom.xml, modules/helpers/inventory-serializer/pom.xml, modules/plugins/jmx/pom.xml, modules/plugins/mod-cluster/pom.xml, pom.xml
Talking Maven to build with Java 8
Here are things that caused build to failed:
* very strict javadoc checker
* animal sniffer, I used this workaround (https://jira.codehaus.org/browse/MANIMALSNIFFER-45) once the bug is solved we may upgrade the animal sniffer
* jmx plugin was starting AS and failing
* ANTLR issue (https://github.com/antlr/antlr3/issues/151) -> upgrading the ANTLR version
* mod_cluster plugin required the dependency on 'jboss-profileservice-spi' (scope = provided)
Before merging, I need to smoke test it and ensure it is still buildable/runnable on jdk6 and jdk7.
=> [BZ 1175774] - Make JBoss ON code base buildable with jdk 8

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/rest/ResourceHandlerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/rest/helper/ResourceCriteriaHelper.java, modules/enterprise/server/jar/src/test/java/org/rhq/enterprise/server/rest/helper/ResourceCriteriaHelperTest.java, modules/integration-tests/rest-api/src/test/java/org/rhq/modules/integrationTests/restApi/ResourcesTest.java
First commit adds:
/resource/{id}/children that could accept the same @QueryParams as /resource
- child resources can now be filtered by name status and category
2nd commit adds:
Added new endpoint : GET /resource/search which supports *ALL* filtering
options from ResourceCriteria class with small exception - it cannot pass
multiple values to filter functions.
2nd commit implementation has an advantage of being generic (if we happen to add a filter to ResourceCriteria, there is a fair chance we don't have to touch REST code, but also a disadvantage - documentation - every parameter could not be documented. I'd like to ask for review .. wheter we want to go this way. We may merge only first commit, but I think the 2nd one adds a real power to REST API to resource filtering
=> Bug 1173096 - Support for Filtering child resources

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/measurement/MeasurementDataManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/storage/StorageClientManager.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/storage/StorageClientManagerMBean.java, modules/enterprise/server/server-metrics/src/main/java/org/rhq/server/metrics/MetricsServer.java, modules/enterprise/server/server-metrics/src/main/java/org/rhq/server/metrics/RawDataInsertedCallback.java, modules/enterprise/server/server-metrics/src/test/java/org/rhq/server/metrics/TimeoutTest.java, modules/enterprise/server/server-metrics/src/test/java/org/rhq/server/metrics/WaitForRawInserts.java, modules/helpers/metrics-simulator/src/main/java/org/rhq/metrics/simulator/MeasurementCollector.java, modules/helpers/metrics-simulator/src/main/java/org/rhq/metrics/simulator/WaitForRawInserts.java, modules/plugins/rhq-server/src/main/resources/META-INF/rhq-plugin.xml
This patch accepts data from the agents if it can write it to the in-memory queue. Otherwise the agent receives an exception and it should resend the data on later time. This is to balance the load on the RHQ Server if the storage node is incapable of accepting configured amounts of writes per second. It also tries to prevent a loss of data by returning it back to the agent for later processing.
=> [BZ 1147098] Queue all the numeric data before writing to the StorageNode

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/operation/GroupOperationJob.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/operation/OperationManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/operation/ResourceOperationJob.java
trying to display orphaned operation schedule
Fixed by removing operation schedules (and unscheduling it) when the user
does not exist anymore. This removal does not happen at the time when user
is deleted, it happens when either - user want's to see such schedule (which
refers to missing user) or when scheduled job is about to run (in this case
it is canceled).
=> Bug 1173164 - Globally uncaught Exception shown in the JBoss ON UI when

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/BaseComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/BaseServerComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/json/UnauthorizedException.java
This fixed BaseServerComponent only - so we display correct resource error,
when insufficient permissions are detected. In all other cases (create
child, operations) it should be obvious from EAP's response which appears on
top of stacktrace. This commit also fixes an issue when there are invalid
user/pass set in pluginConfiguration resource error was not reported
(because InvalidPluginConfigurationException thrown by AS7Connection.execute
was swallowed by getAvailability() code.
=> Bug 1220277 - Correctly handle unsufficient permission errors

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/storage/StorageClientManager.java, modules/enterprise/server/server-metrics/src/main/java/org/rhq/server/metrics/MetricsDAO.java, modules/enterprise/server/server-metrics/src/main/java/org/rhq/server/metrics/StorageSession.java
Check storage node connection aliveness every 4s and recreate the session if check failed twice in a row. This causes the RHQ server to be able to reconnect to the storage nodes in case the whole cluster went down.
=> [BZ 1212627] Recreate storage node sessions if connections are down

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/BaseServerComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/HostControllerComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/StandaloneASComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/helper/HostConfiguration.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/helper/JBossCliConfiguration.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/helper/TruststoreConfig.java, modules/plugins/jboss-as-7/src/main/resources/META-INF/rhq-plugin.xml, modules/plugins/jboss-as-7/src/test/java/org/rhq/modules/plugins/jbossas7/XmlFileReadingTest.java, modules/plugins/jboss-as-7/src/test/java/org/rhq/modules/plugins/jbossas7/helper/JBossCliConfigurationTest.java, modules/plugins/jboss-as-7/src/test/resources/jboss-cli-1.0.xml, modules/plugins/jboss-as-7/src/test/resources/jboss-cli-1.3.xml, modules/plugins/jboss-as-7/src/test/resources/standalone711.xml
Added operation called "Setup CLI" which can change jboss-cli.xml according
to pluginConfiguration properties. It can configure SSL stuff + default
controller host + port. Operation is present for Standalone and Host
Controllers.
=> Bug 1236631 - Add a way to setup SSL settings in jboss-cli.xml

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/core/StartupBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/scheduler/jobs/ReplicationFactorCheckJob.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/storage/StorageNodeOperationsHandlerBean.java
replication_factor of system_auth keyspace is wrong
For system_auth keyspace set replication_factor=clusterSize, so each node
keeps it's own copy of auth data. Created recurrent job which checks
replication_factor for rhq and system_auth keyspacesm when invalid
replication_factor is detected, job tries to fix it and then recommends
running clusterMaintenance
=> Bug 1234912 - Do not authenticate against new storage node when

modules/enterprise/agent/src/main/java/org/rhq/enterprise/agent/AgentConfiguration.java, modules/enterprise/agent/src/main/java/org/rhq/enterprise/agent/AgentConfigurationConstants.java, modules/enterprise/agent/src/main/java/org/rhq/enterprise/agent/AgentUpdateThread.java
Takes the configuration from the AgentConfiguration.
Created the defaults in the AgentConfigurationConstants.
The configuration is taken from the entry: "rhq.agent.agent-update-exit-timeout-msecs".
=> Bug 833547 - make agent shutdown timeout configurable

modules/common/cassandra-ccm/cassandra-ccm-core/pom.xml
If if I don't add this, the build fails because src/main/bundle resources don't get copied over to target/classes
=> Add resource definition or the build fails (Maven 3.3.9)

modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
Bug 1313316 - EAP7 - unable to update configuration of Distributed Cache
Updated all Infinispan subsystem resource types, many attributes have
been drepecated, and while the management interface lets us write
values, the server fails to restart because the attributes are no longer
defined in the subsystem schema file.
Little bonus: added common metrics to cache resource types.
=> Bug 1313316 - EAP7 - unable to update configuration of Distributed Cache

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/CreateResourceDelegate.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/DatasourcesComponent.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/itest/domain/BundleContentHandoverTest.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/itest/domain/SecurityModuleOptionsTest.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/itest/nonpc/AbstractIntegrationTest.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/itest/nonpc/ManagementConnectionPersistenceTest.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/itest/nonpc/ServerGroupTest.java
Bug 1312405 - EAP7 - unable to create xa datasource - At least one xa-datasource-property is required
EAP7, unlike EAP6, wants xa-datasource-properties to be part of the creation operation.
Same applies to regular datasource.
=> Bug 1312405 - EAP7 - unable to create xa datasource - At least one xa-datasource-property is required

modules/helpers/rtfilter-wfly-10-subsystem/src/main/java/org/rhq/helpers/rtfilter/subsystem/wfly10/deployment/RtFilterDeploymentUnitProcessor.java
Bug 1317993 - Application fails to deploy on EAP7 when the rt filter is installed
#getWebMetaData only gives you the content from web.xml, and may be null if deployment descriptor is omitted
#getMergedJBossWebMetaData gives you the content aggregated from all sources (defaults from subsystem config, values from deployment descriptor), and never returns null
=> Bug 1317993 - Application fails to deploy on EAP7 when the rt filter is installed

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/resource/detail/monitoring/CalltimeDataSource.java
Removed formatted value from FIELD_TOTAL attribute, used the value in milliseconds and leave formatted total field just for UI presentation on FIELD_TOTAL_STRING.
=> Bug 1218129 - Calltime metrics sort does not work properly

modules/enterprise/scripting/javascript/src/main/java/org/rhq/scripting/javascript/JavascriptCompletor.java
Defered the check for "(" to allow chaining methods.
"completeParameters" no longer returns the params on the list (to avoid repetitions).
=> Bug 1155104 - CLI auto-complete works incorrectly on second . notation

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/BaseProcessDiscovery.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/BaseServerComponent.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/ServerControl.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/VersionedDomainDeploymentDiscovery.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/VersionedRuntimeDiscovery.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/VersionedSubsystemDiscovery.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/helper/HostConfiguration.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/helper/JBossCliConfiguration.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/helper/ServerPluginConfiguration.java, modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/helper/JBossCliConfigurationTest.java
Removed nativeHost and nativePort settings from EAP7 servers config, as the CLI now connects to the HTTP management port.
Updated discovery class so that when '0.0.0.0' is discovered, '127.0.0.1' is used
Updated component class to log a warning if management host is set to '0.0.0.0'
Changed default from 'localhost' to '127.0.0.1' in HostConfiguration class to avoid troubles when localhost is configured to something else than loopback address
Also, removed upgrade facet from wf10 plugin component classes
=> Bug 1311094 - EAP7 - Native management API port incorrectly detected

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/json/Address.java
Fixes these exceptions: https://bugzilla.redhat.com/show_bug.cgi?id=1313955#c4
The problem was that "Address" removes the "/" that are at the beginning and end of path, thus throwing a java.lang.ArrayIndexOutOfBoundsException when trying to get the value of location key.
example path: subsystem=undertow,server=default-server,host=default-host,location=/
Though at this point I'm not sure if we should allow "/" at the end of some keys (e.g. location) or if it will be OK to only check if "/" is the only value of the last key.
=> Bug 1313955 - Check if "/" is the only value of the last key.

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/BaseProcessDiscovery.java
Bug 1246083 - CLI operations don't work when Native Local Authentication is enabled and Native management API host is set to 0.0.0.0
Update to previous fix: keep 0.0.0.0 in resource name
=> Bug 1246083 - CLI operations don't work when Native Local Authentication is enabled and Native management API host is set to 0.0.0.0

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/measurement/MeasurementOOBManagerBean.java
I assume that if you have permissions to manage the inventory, you should see all resources and all groups and skip the role-group validation for suspect metric report.
=> Bug 1312847 - Report "Suspect Metrics" is empty for user in "All Resources" role

modules/common/wfly-patch-parser/src/main/java/org/rhq/common/wildfly/Patch.java, modules/common/wfly-patch-parser/src/main/java/org/rhq/common/wildfly/PatchParser.java, modules/common/wfly-patch-parser/src/main/java/org/rhq/common/wildfly/PatchProductType.java, modules/enterprise/server/plugins/pom.xml, modules/enterprise/server/plugins/wfly-10-patch-bundle/pom.xml, modules/enterprise/server/plugins/wfly-10-patch-bundle/src/main/java/org/rhq/enterprise/server/plugins/wfly10patch/Wildfly10PatchBundleServerPluginComponent.java, modules/enterprise/server/plugins/wfly-10-patch-bundle/src/main/resources/META-INF/rhq-serverplugin.xml, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/BaseProcessDiscovery.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/BaseServerComponent.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/patching/PatchHandlerComponent.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/patching/PatchHandlerDiscoveryComponent.java, modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
This is still work in progress (requires couple of extra steps to patching process). Adds support for EAP7 instance patching and adds a new server-plugin for EAP7 patching. Checks for product type of the given patch and fixes also EAP6 patching to allow using namespace 1.1 on EAP6.
=> [BZ 1313863] Add support for patching of EAP7 instances

modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
Updated the xml to allow Buffer Cache creation.
=> Bug 1321069 - EAP7 - Undertow - Impossible to add new buffer cache.

modules/enterprise/server/appserver/src/main/scripts/rhq-container.build.xml, modules/helpers/pom.xml, modules/helpers/rtfilter-wfly-10-dist/pom.xml, modules/helpers/rtfilter-wfly-10-dist/src/main/scripts/assembly.xml, pom.xml
Added a new module which produces a single zip with both modules inside.
The zip file name is 'rhq-rtfilter-wfly-10-dist.zip'.
=> Bug 1311140 - EAP7 - missing rt filter modules for eap7

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/Ejb3Component.java, modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
max-pool-size takes the default value, even when is undefined, making it harder for the user to update the configuration as it can't be set along with derive-size.
> 1) Set derive-size and unset max-pool-size
> 2) Save
> 3) Change something else (Timeout or Timeout Unit)
> 4) Save
=> Bug 1314388 - Do not load max-pool-size when derive-size is set.

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/admin/users/UserEditView.java
The `uiCustomizationGrid` was null when creating new user or editing a user that wasn't logged in. This is because the show/hide subsystem configuration is available only to those users that are logged in.
That led to NPE when calling `uiCustomizationGrid.getRecords()` in the post save action that called `getIntegerList()`.
=> Fixing the NPE in the UI when adding or creating a user.

modules/enterprise/server/itests-2/src/test/java/org/rhq/enterprise/server/drift/AbstractDriftServerTest.java, modules/enterprise/server/itests-2/src/test/java/org/rhq/enterprise/server/drift/DriftManagerBeanTest.java, modules/enterprise/server/itests-2/src/test/java/org/rhq/enterprise/server/drift/ManageDriftDefinitionsTest.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/alert/AlertDefinitionManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/configuration/ConfigurationManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/configuration/metadata/ConfigurationMetadataManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/content/ContentSourceManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/drift/DriftManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/drift/DriftTemplateManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/plugin/ServerPluginManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/resource/group/definition/GroupDefinitionManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/resource/metadata/ResourceMetadataManagerBean.java
We knew from observation that drift-related configs were being orphaned in
the DB.  Running some i-tests showed backing configs for drift definitions
being orphaned. This addresses a few different causes:
- improper use of EntityManager.getReference()
- This method is basically an optimized version of EntityManager.find(),
with the difference being that it is not required to go to the DB, and
instead basically wraps the given ID in a proxy for the desired class.
It should generally not be used for reasons outside of using the proxy
to set FK references in other entities, or to explicitly call setters
on the proxy in some circumstances.  It should not be used for an
existence check, a way to perform subsequent gets on the proxy, or
passed to EntityManager.remove(). We were violating all of …
=> Bug 1323332 - Orphaned configuration left in database

modules/enterprise/scripting/javascript/src/main/java/org/rhq/scripting/javascript/JavascriptCompletor.java
Method getContextMatches from JavascriptCompletor now verifies if the baseObject is not null.
=> Bug 875156 - NPE in code completion

modules/enterprise/server/installer/src/main/java/org/rhq/enterprise/server/installer/Installer.java, modules/enterprise/server/installer/src/main/java/org/rhq/enterprise/server/installer/InstallerService.java, modules/enterprise/server/installer/src/main/java/org/rhq/enterprise/server/installer/InstallerServiceImpl.java, modules/enterprise/server/server-control/src/main/java/org/rhq/server/control/command/AbstractInstall.java, modules/enterprise/server/server-control/src/main/java/org/rhq/server/control/command/Upgrade.java
If no storage-schema update is needed, use this one to run only the removeObsoleteColumnFamilies..
=> [BZ 1213812] Add clear columnfamilies option to rhqctl upgrade

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/system/SystemManagerBean.java
Silence warning for system properties PARTITION_EVENT_PURGE and RESOURCE_CONFIG_HISTORY_PURGE…
=> Bug 1364474 - PARTITION_EVENT_PURGE and RESOURCE_CONFIG_HISTORY_PURGE properties remain in the database after 3.3.6

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/alert/definitions/ConditionEditor.java
It was loading the unit of the first available entry and not taking into account the one being edited.
=> Bug 1318747 - Loads the current unit when editing.

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/alert/definitions/NotificationsAlertDefinitionForm.java
Bug 1382649  Attempt to add notification for the second alert definition in JBoss ON UI throws message "Failed to get notification configuration preview".
Removed recursive AlertDefinition seems to solve the problem of deserialization for GWT.
=> Bug 1382649 -Attempt to add notification for the second alert..

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/content/ContentUIManagerBean.java
There was a custom *search* that works fetching all the data.
It was missing the pagination of the results.
=> Bug 1367505 - Trims result to match page controls.

modules/core/plugin-container/src/main/java/org/rhq/core/pc/inventory/InventoryManager.java
This PR address the BZ 1379834, it patches the InventoryManager on the agent side.
Overrides if and only if is a read-only property, this prevents to override user values when there are no plugin default values or the values are dynamic 
I tested this. and It works for me, this is ready for review.
=> Bug 1379834 Prevent override plugin config user values on resource version upgrade

modules/enterprise/gui/portal-war/src/main/java/org/rhq/enterprise/gui/common/framework/PagedDataTableUIBean.java, modules/enterprise/gui/portal-war/src/main/java/org/rhq/enterprise/gui/common/paging/PageControlSettingsUIBean.java
Increases the amount on PagedDataTable to match PageControlSettingsUIBean.
This is a follow up on https://github.com/rhq-project/rhq/pull/285.
When modifying 15/30/45 to scale with the max I forgot to also scale the minimum value.
Also noticed that there was another minimum page that was being used for listing the rows.
=> Bug 1368107 - Update the minimumPagesize to match the new minimum.

modules/core/plugin-container/src/main/java/org/rhq/core/pc/inventory/InventoryManager.java
=> Prevents NPE on mergeExistingResourcePluginConfiguration when property definition doesn't exist anymore.

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/groups/detail/monitoring/table/CompositeGroupD3MultiLineGraph.java
Removes the black circle and non-existent data, adds a dot to mark existent data.
Before:
After:
Before:
After:
=> Bug 1427571 - Solve Unusable group metric graphs.

modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
It currently loads all the buffer-pool's and worker's on the http, https, ajps, etc. So you can choose one.
But it has one (know) issue. While it loads only the needed items (buffer-pools or workers) on each standalone, it mixes all items on profile mode, because the filtering is done at the child after the `PLATFORM`  (see [here](https://github.com/josejulio/rhq/blob/8ae363d095c697a7521fb9ba17a6432ff34d4532/modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/configuration/ConfigurationManagerBean.java#L2854))
Only solution i can think on would be to modify a bit the XSD to extend expressionScope and include a expresionScopeQuery to filter on the type=Profile. 
Alternatives are:
- Modify the XSD (needs to modify the core).
- Put another separator on the …
=> Bug 1433904 - Lists IO subsystem and show options for worker and buffer-pool forms

modules/core/native-system/src/main/java/org/rhq/core/system/NativeSystemInfo.java, modules/core/native-system/src/main/java/org/rhq/core/system/NetworkAdapterInfo.java
This will update displayName of network adapters, using the description instead of the autogenerated "ethX" which might confuse users.
These interfaces don't show when running `ipconfig /all`, but they do appear in the device manager.
=> Bug 1419531 - Use network device description for display name on windows

modules/enterprise/server/plugins/alert-snmp/src/main/java/org/rhq/enterprise/server/plugins/alertSnmp/SNMPComponent.java, modules/enterprise/server/plugins/alert-snmp/src/main/java/org/rhq/enterprise/server/plugins/alertSnmp/SnmpTrapSender.java, modules/enterprise/server/plugins/alert-snmp/src/main/resources/META-INF/rhq-serverplugin.xml
This checks everytime a `ServerPlugin` is initialized if we have a valid value for the transport if not, writes the default configuration onto the database.
// cc @loleary
=> Bug 1455091 - Attemp to fix non valid values when starting the plugin

etc/m2/settings.xml
'gecko' type browser option (such as: <gwt.userAgent>gecko</gwt.userAgent>) causes build to fail as gecko is no-longer supported by GWT. Documented in Bugzilla 1487480 (https://bugzilla.redhat.com/show_bug.cgi?id=1487480).
https://stackoverflow.com/a/7992793/6328995
https://gwt.googlesource.com/gwt/+/master/user/src/com/google/gwt/useragent/UserAgent.gwt.xml
(originally https://github.com/rhq-project/rhq/pull/325)
=> Remove browser type gecko, no longer supported

modules/enterprise/binding/src/main/java/org/rhq/bindings/client/ResourceClientProxy.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/content/ContentManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/content/ContentManagerRemote.java
Not tested yet, but this should fix BZ-1420712 and BZ-1420717
Don't merge yet.
=> Force  updateBackingContent to discover the new package in sync manner.

modules/enterprise/server/plugins/alert-snmp/src/main/java/org/rhq/enterprise/server/plugins/alertSnmp/SNMPComponent.java
I was getting `could not initialize proxy - no Session` when trying to load the configuration from the ServerPlugin. That issue wasn't showing on RHQ.
I build this plugin on RHQ and installed it on JON, and was working as expected with this change.
=> Bug 1455091 - Uses configuration being sent instead of fetching

modules/enterprise/gui/coregui/src/main/webapp/org.rhq.coregui.CoreGUI/sc/skins/CoreGUI/skin_styles.css
Instead of resetting to auto all the z-index which are managed by gwt
Give the message div the highest (32bit max signed int) priority
@rubenvp8510 please review
=> Bug 1532749, 1532743 - Keep message parent div always on top (z-index)

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/BaseProcessDiscovery.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/BaseServerComponent.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/WebRuntimeDiscoveryComponent.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/helper/ServerPluginConfiguration.java, modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
Importing local EAPs follow a similar flow as the autodiscovery
and are allowed to use operations.
--
Note: You can't manual import (Marking them as "Local") a resource that has been autodiscovered, because they share the same id.
To bypass this, one can, rename $JBOSS_HOME folder, start and manually import before the next autodiscovery.
edit:
Removed the "local" attribute. Now it tries to load the manually imported resource as "local", and falls back to "remote" if can't find all the required information.
A "remote" server can't execute some operations (because we need access to some files).
=> Bug 1538697 - Allow to specify if manually imported EAP as local

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/helper/ServerPluginConfiguration.java, modules/plugins/jboss-as-7/src/test/java/org/rhq/modules/plugins/jbossas7/WebRuntimeDiscoveryComponentTest.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/helper/ServerPluginConfiguration.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/WebRuntimeDiscoveryComponentTest.java
Also Fix tests related to manually adding a server
It was failing because two things:
- We didn't mock the `getServerPluginConfiguration` method, it wasn't being used on these tests.
- We didn't provide a default value in case "isLocal" is `null`, this could happen when importing using an old version and then upgrading, defaults to False, old versions always used the "Remote" path.
=> Bug 1537720, 1538697 - Adds default value for isLocal

modules/common/jboss-as-dmr-client/src/main/java/org/rhq/common/jbossas/client/controller/InfinispanJBossASClient.java, modules/common/jboss-as-dmr-client/src/main/java/org/rhq/common/jbossas/client/controller/SecurityDomainJBossASClient.java, modules/enterprise/server/installer/src/main/java/org/rhq/enterprise/server/installer/ServerInstallUtil.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/core/jaas/DelegatingLoginModule.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/rest/UserHandlerBean.java
- Set SecurityDomain[RHQRESTSecurityDomain] cache-type to infinispan
- Creates infinispan cache at server install
(named security, which is what cache-type=infinispan uses)
- Creates new endpoint /user/logout to force the removal of the
logged user cache
Reverts https://github.com/rhq-project/rhq/commit/5837457f16bdd16d7c956bfbeb549de0fe478e13 (i.e. reverts the revert)
This make the following changes to `standalone-full.xml` while installing:
- security-domain name="RHQRESTSecurityDomain" cache-type is changed from `default` to `infinispan`
- The following `cache-container` is created:
```xml
<cache-container name="security" default-cache="auth-cache" jndi-name="java:jboss/infinispan/security">
<local-cache name="auth-cache">
<eviction strategy="LRU" max-entries="1000"/>
<expiration …
```
=> Bug 1542125 - Allows rest user to logout to be able to refresh its permissions

modules/core/domain/src/main/java/org/rhq/core/domain/configuration/Configuration.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/configuration/ConfigurationManagerBean.java
I need to modify the initial solution proposed, that is due to a deadlock on Oracle DB when the deletion of the old configurations in a config replacement is performed.
This occurs because the there is a lot of FK pointing to RHQ_CONFIG table that doesn't have indices, so Oracle decides to acquire a lock for "child" tables. At some point, we have two transactions that have a shared lock and want to acquire an exclusive lock for some of those tables, but both need to wait to the other release the shared lock,  in that scenario we have a deadlock. This happens especially in high concurrent methods like `setResourceConfiguration`.
To avoid this, I prefer to do an update on the existing row, instead of a whole replacement of the config row. This is what I tried to do in this PR.
@josejulio …
=> BZ 1418034 - Try to update configurations instead of replace/delete it

modules/enterprise/server/installer/src/main/java/org/rhq/enterprise/server/installer/InstallerServiceImpl.java, modules/enterprise/server/installer/src/main/java/org/rhq/enterprise/server/installer/ServerInstallUtil.java
- Allows the installer to write jboss.tx.node.id even if not set at install time
- Sets jackson.deserialization.whitelist.packages
=> Bug 1630170 - Set the same properties as jboss-cli-commands.txt

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/JBossProductType.java
JBossProductType.WILDFLY8 was removed as part of the work done in
BZ-1337983. As this type is part of the plug-in API, it should not have
been removed. This adds the type back in so that any references to the
type in previously released plug-ins will not fail.
=> [BZ-1647619] Added unsupported WILDFLY8 type back for compatibility

modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
- subsystem=EJB3 doesn't have a derive-size/max-pool-size,
thus Ejb3Component is not required in this case.
- Removing default-clustered-sfsb-cache as is deprecated and read-only
=> Bug 1655639 and 1655644 - Unable to update EJB3 resource configuration

modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
It has been replaced by the already supported
jpa entity (hibernate-persistence-unit)
=> Bug 1691697 - Remove unused entity-bean resource.
