rhq-project/rhq

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/AbstractVersionedSubsystemDiscovery.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/BaseComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/DeploymentComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/DomainDeploymentComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/HostControllerComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/ServerGroupComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/helper/Deployer.java
Support for updating package content for versioned deployments. This commit
also extracts code for creating deployment resources into Deployer class.
=> Bug 1188751 - Deploying Versioned WAR package from repository to JBOSS EAP 6  deployment resource fails

modules/plugins/tomcat/src/main/java/org/jboss/on/plugins/tomcat/TomcatDatasourceDiscoveryComponent.java
Hi everyone,
We also need this commit on release/jon3.3.x
Could anyone please run a cherry pick to that branch ?
Cheers
=> Fix BZ 1201269

modules/plugins/tomcat/src/main/java/org/jboss/on/plugins/tomcat/TomcatWarComponent.java, modules/plugins/tomcat/src/main/resources/META-INF/rhq-plugin.xml
Hi there,
We also need this commit in release/jon3.3.x.
Could anyone please do the cherry-pick ?
Cheers.
=> Fix JWS-54 - Add Tomcat7 support

modules/plugins/apache/src/main/java/org/rhq/plugins/apache/ApacheServerComponent.java
Hello,
We also need this fix on jon3.3.x.
Can someone please do the cherry-pick ?
Cheers,
Maxime Beck
=> BZ 1205676

modules/plugins/apache/src/main/java/org/rhq/plugins/apache/ApacheServerDiscoveryComponent.java
Hi there,
Can this commit please be cherry-pick on jon.3.3.x ?
Cheers,
Maxime Beck
=> Fix JWS-116 - JON Httpd: Path To Contain Virtual Hosts Files

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/ServerControl.java
Anytime plugin attempts to run CLI in connected mode, we execute  dummy CLI
command to detect whether SSL certificate needs to be accepted (manual
intervention needed). This dummy command is executed prior the original
command so we can make sure the original command is not blocked forever by
CLI asking for user input. In case we detect (based on dummy command
output), we return special implementation of ProcessExecutionResults to
caller which holds results from dummy process with error message produced by
CLI representing certificate details.
This commit does not fix 100% Bug 1226413, but  prevents blocked CLI process
as part of rhq:handover action or CLI operation.
=> Bug 1226413 - Implementation of rhq:handover doesn't account for EAP https connections

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/ServerControl.java
using SSL and jboss-cli does not yet trust certs
Fixed potential OOM caused by EAP 6.4.x which is constantly filling stdout
when waiting for user to accept ssl cert.
Fixed cleaning up java process (executed dummy CLI command), which could
survive, it's parent because it got detached from it.
=> Bug 1226413 - Bundle rhq:handover can hang when management interface is

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/storage/StorageNodeOperationsHandlerBean.java
Increase timeout for all long running storage node operations to 7 days.
=> Bug 1232847 - Increase timeout for repair operation

modules/enterprise/binding/src/main/java/org/rhq/bindings/output/TabularWriter.java
Renamed the print overloaded methods to only leave one and avoid ambiguities.
void print(Object)
void printCollection(Collection)
void printConfiguration(Configuration)
...
The print method also verify the input to call the correct method.
=> Bug 907897 - pretty.print(null) fails

modules/plugins/apache/src/main/java/org/rhq/plugins/apache/ApacheServerComponent.java
It was stopping at the first match.
=> Fix JWS-118

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/resource/group/ResourceGroupManagerBean.java
Deletes all the BundleDestinations using BundleManager in the deleteResourceGroup (to avoid FK deletion issues of missing CASCADE.DELETE)
Should not be merged to master, master has correct fix for DB.
=> [BZ 1206084] Delete all the BundleDestinations before removing ResourceGroup

modules/enterprise/agent/src/main/java/org/rhq/enterprise/agent/i18n/AgentI18NResourceKeys.java, modules/enterprise/agent/src/main/java/org/rhq/enterprise/agent/promptcmd/DiscoveryPromptCommand.java
Swapped the default discovery behavior with a --dry-run option and the  --full option.
(The new default is --full).
=> Bug 753204 - Discovery --full should be the default

modules/enterprise/server/ear/pom.xml, modules/plugins/validate-all-plugins/pom.xml, modules/plugins/wfly-10/pom.xml, modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml, pom.xml
Added the new plugin to the EAR build
Also, added it to plugin validation module and created the version
property in parent POM.
Fixed a couple of typos.
=> Bug 1315203 - Plugin for eap7 is not deployed

modules/enterprise/server/appserver/src/main/downloadable-resources/connectors/README.txt, modules/enterprise/server/appserver/src/main/scripts/rhq-container.build.xml, modules/helpers/pom.xml, modules/helpers/rtfilter-wfly-10-subsystem/pom.xml, modules/helpers/rtfilter-wfly-10-subsystem/src/main/java/org/rhq/helpers/rtfilter/subsystem/wfly10/RtFilterExtension.java, modules/helpers/rtfilter-wfly-10-subsystem/src/main/java/org/rhq/helpers/rtfilter/subsystem/wfly10/RtFilterSubsystemAdd.java, modules/helpers/rtfilter-wfly-10-subsystem/src/main/java/org/rhq/helpers/rtfilter/subsystem/wfly10/RtFilterSubsystemDefinition.java, modules/helpers/rtfilter-wfly-10-subsystem/src/main/java/org/rhq/helpers/rtfilter/subsystem/wfly10/RtFilterSubsystemRemove.java, modules/helpers/rtfilter-wfly-10-subsystem/src/main/java/org/rhq/helpers/rtfilter/subsystem/wfly10/deployment/RtFilterDeploymentUnitProcessor.java, modules/helpers/rtfilter-wfly-10-subsystem/src/main/resources/META-INF/services/org.jboss.as.controller.Extension, modules/helpers/rtfilter-wfly-10-subsystem/src/main/resources/module/main/module.xml, modules/helpers/rtfilter-wfly-10-subsystem/src/main/resources/org/rhq/helpers/rtfilter/subsystem/wfly10/LocalDescriptions.properties, modules/helpers/rtfilter-wfly-10-subsystem/src/main/resources/schema/rtfilter-subsystem.xsd, modules/helpers/rtfilter-wfly-10-subsystem/src/main/scripts/module-assembly.xml, modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml, pom.xml
Added new rtfilter-wfly-10-subsystem
Added new rtfilter-wfly-10-subsystem to downloads section
Fixed Web Runtime component (now at path subsystem=undertow)
Verified Calltime metric collection
=> Bug 1311140 - EAP7 - missing rt filter modules for eap7

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/ModuleOptionsComponent.java
Because this subsystem  is deprecated, I just ignore the exception.
=> Bug 1320289 - Exception when trying to edit Module options from Security subsystem

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/UndertowComponent.java, modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
Creates JSP and Websockets settings nodes when trying to create Servlet Container.
=> Bug 1321941 - EAP7 - Undertow - new created Servlet Container not loaded

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/dashboard/portlets/groups/GroupMetricsPortlet.java
Also, in renderData validates when commaDelimitedList is empty, in order to prevent throwing an exception in GWT Debug mode.
=> Bug 1261890 - Metrics are not properly updated/refreshed in JON UI

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/rest/AbstractRestBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/rest/GroupHandlerBean.java
- Don't pull in all resources for every fetched group
- Avoid umbrella transaction
@burmanm please review
=> Bug 1337995 REST fetch of groups doesn't scale

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/measurement/MeasurementDataManagerBean.java
Test if value is not null before using it.
=> Bug 1320478 - NPE in server.log Error persisting trait data

modules/plugins/jboss-as-7-jmx/src/main/java/org/rhq/modules/plugins/jbossas7/jmx/ApplicationMBeansDiscoveryComponent.java, modules/plugins/jboss-as-7/intentional-api-changes-since-4.13.0.xml, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/BaseProcessDiscovery.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/BaseServerComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/JBossProductType.java, modules/plugins/jboss-as-7/src/test/java/org/rhq/modules/plugins/jbossas7/ProductTypeTest.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/BaseServerComponent.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/JBossProductType.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/ProductTypeTest.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/itest/AbstractServerComponentTest.java, modules/plugins/wfly-10/src/test/java/org/rhq/modules/plugins/wildfly10/itest/nonpc/InterruptibleOperationsTest.java
Remove Wildfly8 support, change AS7 plugin to only accept apiVersion 1.x and Wildfly10 plugin to accept only apiVersion 4.x. Also add JDG7 detection to wfly-10 plugin.
=> Change JBossProductType detection to apiVersion only

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/content/ContentManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/purge/JPADriftFilePurge.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/purge/PurgeTemplate.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/resource/ResourceManagerBean.java, modules/plugins/postgres/src/main/java/org/rhq/plugins/postgres/PostgresDatabaseComponent.java, modules/plugins/postgres/src/main/java/org/rhq/plugins/postgres/PostgresServerComponent.java, modules/plugins/postgres/src/main/resources/META-INF/rhq-plugin.xml
Add a new operation to clean orphaned large objects from the database
=> [BZ 1381720] Clean orphaned large objects

modules/enterprise/gui/portal-war/src/main/java/org/rhq/enterprise/gui/common/paging/PageControlSettingsUIBean.java
This increases the number of items per page on every gui/portal-war
that uses the PageControlSettingsUIBean.
=> Bug 1368107 - Increase the amount of items per page.

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/groups/detail/monitoring/table/CompositeGroupD3GraphListView.java, modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/groups/detail/monitoring/table/CompositeGroupD3MultiLineGraph.java
=> Bug 1236021 - Adds a circle to non NAN measurements.

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/cloud/StorageNodeManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/storage/StorageNodeOperationsHandlerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/storage/StorageNodeOperationsHandlerLocal.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/storage/StorageNodeOperationsHandlerRemote.java
Give user the ability to force storage node out of maintenance mode as well as change some behavior for decommission and maintenance mode flag.
=> [BZ 1272328] Ability to decommission maintenance mode storagenode'

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/content/ContentManagerBean.java, modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/content/ContentManagerLocal.java
- Added validations for unlink only on Postgres
- Put unlink process as part of other transaction
- One transaction per package.
@josejulio Could you please help me to test and review? Thank you!!
=> BZ-1386913 Separate transactions for remove bits.

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/dashboard/portlets/recent/events/AbstractRecentEventsPortlet.java
=> Bug-1413088  Not fetching source in the Events portlet

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/resource/detail/ResourceTitleBar.java, modules/enterprise/gui/coregui/src/main/resources/org/rhq/coregui/client/Messages.properties
- Set availability to unknown on timeout
=> Bug 1380471 - Check for timeouts when getting live availability

modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/common/graph/MetricGraphData.java, modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/resource/detail/monitoring/table/MetricsGridFieldName.java, modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/resource/detail/monitoring/table/MetricsTableView.java, modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/inventory/resource/detail/monitoring/table/MetricsViewDataSource.java, modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/util/MeasurementConverterClient.java, modules/enterprise/gui/coregui/src/main/java/org/rhq/coregui/client/util/MeasurementUtility.java
@josejulio  @burmanm  Could you please review?
=> [Bug 1447965] Use MetricDisplaySummary fit units for chart scaling.

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/NamingBindingComponent.java, modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
=> BZ 1477945 Added environment and cache fields to subsystem=naming/binding entries

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/DeploymentComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/HostControllerComponent.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/Redeployer.java, modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/StandaloneASComponent.java
@josejulio Could you please review?
//cc @burmanm
=> Bug 1503826 - Change redeploy check, using deploy name instead of runtime-name

modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/DeploymentComponent.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/HostControllerComponent.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/Redeployer.java, modules/plugins/wfly-10/src/main/java/org/rhq/modules/plugins/wildfly10/StandaloneASComponent.java
This is the same as BZ 1503826  but this is for EAP7
@burmanm @josejulio
=> Bug 1504148 - Change redeploy check, using deploy name instead of runtime-name

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/configuration/ConfigurationManagerBean.java
@josejulio Could you please review,
This only mitigates the problem, there is still some orphaned configurations that appear from time to time, I'm not sure where that comes from.
=> Bug 1418034 - Fix orpahaned configuration when update config parameters.

modules/enterprise/server/jar/src/main/java/org/rhq/enterprise/server/rest/AlertDefinitionHandlerBean.java
@burmanm can you please review?
=> Bug 1532387 - Create child alerts for groups and templates

modules/plugins/jboss-as-7/src/main/java/org/rhq/modules/plugins/jbossas7/NamingComponent.java
=> BZ-1652063 Validate for null on environment property

modules/plugins/wfly-10/src/main/resources/META-INF/rhq-plugin.xml
=> Bug 1650479 - Remove handoff-executor from long/short running threads

modules/plugins/jboss-as-7/src/main/resources/META-INF/rhq-plugin.xml
=> Bug 1650478 - Remove handoff-executor from long/short running threads
